### PR TITLE
13058 COLIN API failure - Front and Backend Change validation of the first name field in Coop IA UI and/or Corp Party table

### PR DESCRIPTION
**Pull request by lewischenstudio**
*Issue #:* [/bcgov/entity#13058](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/13058)

*Description of changes:*
- temporarily change the max length of "firstName" to 20 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the business-schemas license (Apache 2.0).

### CODE REVIEW

**Comment by lewischenstudio** [comment]
Please do not merge the PR. Frontend UIs, i.e., Create UI, are required to make changes before we merge this PR to main.

**Review by argush3 — APPROVED** [review]
looks good.  just want to see if CI passes 

@vysakh-menon @lekshmimallika-aot can you assign the PR to @lewischenstudio when you have a second?  i don't have access to the repo

**Review by lekshmimallika-aot — APPROVED** [review]

**Review by vysakh-menon-aot — APPROVED** [review]

**Comment by lewischenstudio** [comment]
Thanks guys. I'll let you know when I finish the UIs.

**Comment by severinbeauvais** [comment]
Hey @lewischenstudio , check out https://github.com/bcgov/bcrs-shared-components/pull/139.

**Comment by lewischenstudio** [comment]
I've also updated the "middleInitial" length to 20 as requested in this [PR](https://github.com/bcgov/business-create-ui/pull/429).

**Pull request merged**
