### PR TITLE
Correction schema updates

### PR DESCRIPTION
**Pull request by lekshmimallika-aot**
*Issue #:* /bcgov/entity#12904

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the business-schemas license (Apache 2.0).

### CODE REVIEW

**Review by severinbeauvais — APPROVED** [review]
LGTM.

So this is still valid, right?
```
filing: {
  header: {...},
  business: {...},
  correction: {...}.
  incorporationApplication: {...}
}
```

What should a SP/GP correction look like?

**Comment by lekshmimallika-aot** [comment]
> LGTM.
> 
> So this is still valid, right?
> 
> ```
> filing: {
>   header: {...},
>   business: {...},
>   correction: {...}.
>   incorporationApplication: {...}
> }
> ```
> 
> What should a SP/GP correction look like?

Yes. This is valid

**Review by vysakh-menon-aot — APPROVED** [review]

**Review by argush3 — APPROVED** [review]

**Comment by severinbeauvais** [comment]
> SP/GP correction looks like CORRECTION_CHANGE_OF_REGISTRATION/ CORRECTION_REGISTRATION in the schema_data

I thought we were going to a "business snapshot" model -- the correction would contain all entity data. Some of this data might not fit in changeOfRegistration/ registration schemas, and certainly won't fit in annualReport/ changeOfDirectors/ changeOfAddress schemas when we move those from Filings UI (Corrections 1.0) to Edit UI (full corrections).

**Comment by lekshmimallika-aot** [comment]
> > SP/GP correction looks like CORRECTION_CHANGE_OF_REGISTRATION/ CORRECTION_REGISTRATION in the schema_data
> 
> I thought we were going to a "business snapshot" model -- the correction would contain all entity data. Some of this data might not fit in changeOfRegistration/ registration schemas, and certainly won't fit in annualReport/ changeOfDirectors/ changeOfAddress schemas when we move those from Filings UI (Corrections 1.0) to Edit UI (full corrections).

This is a business snapshot model and it also gives you flexibility to send only the objects that you changed. For example , if you make any changes to a party object you send the "parties" object in the request.

**Comment by severinbeauvais** [comment]
> This is a business snapshot model and it also gives you flexibility to send only the objects that you changed. For example , if you make any changes to a party object you send the "parties" object in the request.

So, if a COA is being corrected, then I can also attach the parties object?
```
filing:
  correction: {...},
  changeOfAddress: {
    parties: {...}
  }
}
```

**Comment by severinbeauvais** [comment]
> So the model we are targeting is it does not matter the filing from which we launch correction, you should be able to correct anything in a business right?

Yes, that is my understanding.

> In that case there will not be a section like changeOfAddress in correction 2.0. 'parties' will be in the correction object. Till that is implemented for CP and BEN, correction 1.0 will continue to work as it is

Are you saying CP COA correction 2.0 will look like this?
```
filing:
  correction: {...},
  changeOfAddress: {...},
  correction: {
    parties: {...}
  }
}
```

**Pull request merged**
